### ISSUE TITLE
Add reporter of test coverage to sdk-java CI

### ISSUE THREAD

**Issue by afrittoli** [cdevents/sdk-java#49]

**Comment by rjalander** [comment]
This issue is addressed as part of the PR: https://github.com/cdevents/sdk-java/pull/63/commits/f7f24f41f580ba0c5dd0c8c636e6ac036da15861
by creating [surefire-reports](https://github.com/cdevents/sdk-java/actions/runs/7488315768/artifacts/1162208187) under test workflow, this will give a detailed test coverage report, that can be downloaded from the Summary page.
![{2E6FA220-9E1B-4387-9366-47C9055A91BA}](https://github.com/cdevents/sdk-java/assets/97948659/4e9e66c5-225d-43f2-868b-e75115f555e6)
