### ISSUE TITLE
Validating CDEvent fails if not setting Optional fields

### ISSUE THREAD

**Issue by rjalander** [cdevents/sdk-java#51]
As per the spec for most of the [events](https://github.com/cdevents/spec/blob/v0.1.2/core.md#pipelinerun-queued) **subject.content** filds are optional, but validating the event against [jsonschema](https://github.com/cdevents/spec/blob/v0.1.2/schemas/pipelinerunqueued.json) fails if not setting these optional fields when [creating an event,](https://github.com/cdevents/sdk-java/blob/main/src/main/java/dev/cdevents/CDEvents.java#L76)

An example **pipelineRunQueued** events fails without setting these optional fields **source, pipelineName, url**
CDEvent validation failed with errors `[ $.subject.source: null found, string expected, $.subject.content.pipelineName: null found, string expected, $.subject.content.url: null found, string expected ]`

**Comment by rjalander** [comment]
Is this something we need to allow string and null(for optional fields) something like `"type": ["string","null"]` in the [jsonschema](https://github.com/cdevents/spec/blob/v0.1.2/schemas/pipelinerunqueued.json#L56-L61), wondering how it is handled in sdk-go I don't see it's having default values for optional fields to pass this schema validation?

**Comment by afrittoli** [comment]
I don't think this is something in the jsonschema.

In the go sdk i had a similar issue because I wasn't using pointers in the types, and the JSON renderer was than producing the zero value for the types, which is not allowed by the schema i.e. an optional field should either not be there at all or, if it's there it should meet the schema requirements.

The Java libraries will most likely behave differently from the go ones, but it might be an issue in a similar kind of area.

**Comment by rjalander** [comment]
If I change the default values to empty for optional fields, the validation goes fine.
I think the same way it is handled in sdk-go with [omitempty](https://github.com/afrittoli/cdevents-sdk-go/blob/527d4a1aca5e8d0df24813df5ad65d049fc8d312/pkg/api/pipelinerunqueued.go#L34-L37), If I am not wrong.

**Comment by afrittoli** [comment]
Yes indeed.
Specifically for go, omitempty only with pointers.

**Comment by rjalander** [comment]
Also, comparing the datatypes of the fields for the events in **jsonschema(/go-sdk)** vs **spec**, most of the types in jsonschema are `string` but they are defined as `URI`, `Enum`, `Purl `and `URI-Reference`. 
I think it should follow the rules from spec right?, In that case all the default values will be set to `null`

**Comment by afrittoli** [comment]
Thanks @rjalander - you are right, the spec is more specific than the JSONSchema today in a few places.

For URI and URI reference, that's something that was hopefully fixed in https://github.com/cdevents/spec/pull/116 - so that should solve itself once you work on the latest version.

For enums, AFAIK everything which is an enum is defined so in the schema, if you have examples where that is not the case please let me know, so we can fix that.

For purls, I don't think it's possible to enforce that format today in JSONSchemas. That's something we can work on together with the purl and JSONSchema communities. In the meanwhile, we have a gap between what can be enforced in the schema and what is documented in the spec. 
When we work on generating the spec docs from the schema, we'll need a way to handle that.
In terms of SDKs, for the golang SDK for now I have a hack in place, it looks for fields called "artifactId" and it enforces the "purl" format for them. In future we may need a more general solution for that.

**Comment by afrittoli** [comment]
That would weaken the schema, it would say that we allow for the field to be set and empty, which I would prefer to avoid.

Isn't there any option in the java library that renders to JSON to not render unset fields?

**Comment by rjalander** [comment]
Ok, 
yes we can use jackson library when serializing the object to exclude optional unset/null fields, before validating against jsonschema.
This way the resultant CDEvent data will not have any optional fields itself when unset, If that is fine.(This might be different when comparing with the go-sdk, the optional fileds set to empty when unset in the CDEvent data) ?

**Comment by afrittoli** [comment]
Empty optional fields are not rendered in the go SDK, or else the json would fail validation, like it happened for the java sdk

**Comment by rjalander** [comment]
Ok, will go with this and create a PR for not to render optional fields with null. Thank you.

**Comment by rjalander** [comment]
Closing, as the PR to fix the issue is merged. https://github.com/cdevents/sdk-java/pull/55
